mf_embedding_size: 64
mlp_embedding_size: 64
mlp_hidden_size: [256,256,256]
dropout_prob: 0.3
mf_train: True
mlp_train: True

use_pretrain: False
mf_pretrain_path: ~
mlp_pretrain_path: ~
learning_rate: 5e-4